CREATE TABLE block_identifiers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hash BYTEA UNIQUE NOT NULL CHECK (octet_length(hash) = 32)
);

CREATE TABLE levels (
    level BIGINT PRIMARY KEY CHECK (level > 0),
    size BIGINT NOT NULL CHECK (size > 0),
    daa_score BIGINT NOT NULL DEFAULT 9223372036854775807 CHECK (daa_score >= 0)
);

CREATE TABLE blocks (
    id BIGINT PRIMARY KEY REFERENCES block_identifiers(id),
    timestamp BIGINT NOT NULL,
    daa_score BIGINT NOT NULL CHECK (daa_score >= 0 AND daa_score < 9223372036854775807),
    level BIGINT NOT NULL CHECK (level > 0),
    slot BIGINT NOT NULL CHECK (slot >= 0),
    selected_parent_id BIGINT NOT NULL REFERENCES block_identifiers(id),
    color SMALLINT NOT NULL CHECK (color BETWEEN 0 AND 2),
    is_in_vspc BOOLEAN NOT NULL,
    blue_merge_set BIGINT[] NOT NULL,
    red_merge_set BIGINT[] NOT NULL,
    UNIQUE (level, slot)
);

CREATE TABLE parents (
    child_id BIGINT NOT NULL,
    parent_id BIGINT NOT NULL,
    child_level BIGINT NOT NULL CHECK (child_level > 0),
    child_slot BIGINT NOT NULL CHECK (child_slot >= 0),
    parent_level BIGINT NOT NULL CHECK (parent_level >= 0),
    parent_slot BIGINT NOT NULL CHECK (parent_slot >= 0),
    PRIMARY KEY (child_id, parent_id),
    CHECK (parent_level > 0 OR parent_slot = 0)
);

CREATE INDEX blocks_vspc_sink_idx ON blocks (id DESC) WHERE is_in_vspc;
CREATE INDEX parents_child_coordinate_idx ON parents (child_level, child_slot);
CREATE INDEX parents_parent_coordinate_idx ON parents (parent_level, parent_slot) WHERE parent_level > 0;
CREATE INDEX levels_daa_score_level_idx ON levels (daa_score DESC, level DESC);
