[package]
name = "kgi-node"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
async-trait.workspace = true
kaspa-consensus-core.workspace = true
kaspa-core.workspace = true
kaspa-grpc-client.workspace = true
kaspa-notify.workspace = true
kaspa-rpc-core.workspace = true
kgi-core = { path = "../kgi-core" }
kgi-model = { path = "../kgi-model" }
log.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
url.workspace = true

[dev-dependencies]
kaspa-grpc-core.workspace = true

[lints]
workspace = true
